/**
 * This class is generated by jOOQ
 */
package org.zenja.havideo.user.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.1.0"},
                            comments = "This class is generated by jOOQ")
public class Havideo extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 793323555;

	/**
	 * The singleton instance of havideo
	 */
	public static final Havideo HAVIDEO = new Havideo();

	/**
	 * No further instances allowed
	 */
	private Havideo() {
		super("havideo");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(org.zenja.havideo.user.jooq.tables.User.USER);
	}
}
