/**
 * This class is generated by jOOQ
 */
package org.zenja.havideo.user.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the havideo schema
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.1.0"},
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({"unchecked"})
public class Keys extends org.jooq.impl.AbstractKeys {

	// IDENTITY definitions

	// UNIQUE and PRIMARY KEY definitions
	public static final org.jooq.UniqueKey<org.zenja.havideo.user.jooq.tables.records.UserRecord> KEY_USER_PRIMARY = createUniqueKey(org.zenja.havideo.user.jooq.tables.User.USER, org.zenja.havideo.user.jooq.tables.User.USER.ID);

	// FOREIGN KEY definitions

	/**
	 * No instances
	 */
	private Keys() {}
}
