/**
 * This class is generated by jOOQ
 */
package org.zenja.havideo.user.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in havideo
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.1.0"},
                            comments = "This class is generated by jOOQ")
public final class Tables {

	/**
	 * The table havideo.user
	 */
	public static org.zenja.havideo.user.jooq.tables.User USER = org.zenja.havideo.user.jooq.tables.User.USER;

	/**
	 * No instances
	 */
	private Tables() {}
}
