/**
 * This class is generated by jOOQ
 */
package org.zenja.havideo.user.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.1.0"},
                            comments = "This class is generated by jOOQ")
public class UserRecord extends org.jooq.impl.UpdatableRecordImpl<org.zenja.havideo.user.jooq.tables.records.UserRecord> {

	private static final long serialVersionUID = -601666197;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(org.zenja.havideo.user.jooq.tables.User.USER.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(org.zenja.havideo.user.jooq.tables.User.USER.ID);
	}

	/**
	 * An uncommented item
	 */
	public void setUsername(java.lang.String value) {
		setValue(org.zenja.havideo.user.jooq.tables.User.USER.USERNAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getUsername() {
		return getValue(org.zenja.havideo.user.jooq.tables.User.USER.USERNAME);
	}

	/**
	 * An uncommented item
	 */
	public void setPassword(java.lang.String value) {
		setValue(org.zenja.havideo.user.jooq.tables.User.USER.PASSWORD, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getPassword() {
		return getValue(org.zenja.havideo.user.jooq.tables.User.USER.PASSWORD);
	}

	/**
	 * Create a detached UserRecord
	 */
	public UserRecord() {
		super(org.zenja.havideo.user.jooq.tables.User.USER);
	}
}
